# Generated by Django 4.0.1 on 2023-01-08 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_alter_employee_hire_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='last_nmae',
            new_name='last_name',
        ),
    ]
